name: Pull and Push

on: [ workflow_dispatch ]

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Git settings
        run: |
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ secrets.NAME }}"
      - name: Pull and Push
        run: |
          git clone https://github.com/minetaro12/new-minetaro12pages ../origin
          cp -r ../origin/content/posts/* .
          git add .
          git commit -m "Update"
          git push
        
